// ---------------------------------------------------------------------------
// miracles.js - belief, casting, the four miracles, and alignment.
//
// BELIEF is generated by villagers, scaled by how happy the town is. It is the
// only thing miracles cost, so a cruel god who lets his people starve slowly
// loses the power to be cruel.
//
// CASTING is a held key: Ctrl turns the mouse into a casting tool. The wheel
// picks which miracle, a left click places it, and letting go of Ctrl puts it
// away. There is no mode to get stuck in and nothing to disarm - the state
// lasts exactly as long as you hold the key.
//
// ALIGNMENT is one float in -1..+1, moved by deeds reported on the event bus
// and by miracles cast. It drives no mechanics directly; it changes how the
// world *looks*, by recolouring and by swapping between two geometry variants.
//
// Publishes state.miracles.
// ---------------------------------------------------------------------------
import * as THREE from 'three';
import { MIRACLE, MIRACLES, ALIGNMENT, WORLD, TOWN, COMBAT, PRAYER} from './state.js';

/**
 * Miracles are ARMED from the grimoire and placed with a click.
 *
 * They used to be drawn as $1-style gestures on the right button. That was a
 * pleasing thing to build and a poor thing to use: a miracle you meant to cast
 * could fail because your circle came out too oval, the failure message told
 * you your handwriting was bad, and the entire right button was spent on it.
 * Arming from the grimoire is unambiguous, costs one click, and frees the right
 * button for the creature - which needed a way to be told where to go far more
 * than casting needed to be a test of draughtsmanship.
 */

export function initMiracles(state) {
  const terrain = state.terrain;

  // --- alignment ------------------------------------------------------------
  let alignTarget = 0;
  state.alignment = 0;

  /** When the last cruel deed landed. Drives penance - see ALIGNMENT. */
  let lastCrueltyAt = -999;
  /**
   * How many prayers have gone unanswered in a row. Above
   * PRAYER.NEGLECT_BLOCKS_PENANCE it suspends penance entirely - see there for
   * why, and for the arithmetic that made it necessary.
   */
  let neglectStreak = 0;

  function shiftAlignment(amount, why) {
    // The redemption curve. A kindness counts for more the further you have
    // fallen, and a further cruelty costs less once you are already down there.
    // Both effects scale with depth and disappear at neutral, so a player who
    // has never gone into the red never notices this exists.
    const depth = Math.max(0, -alignTarget);
    let scaled = amount;
    if (depth > 0) {
      scaled = amount > 0
        ? amount * (1 + ALIGNMENT.REDEMPTION * depth)
        : amount * (1 - ALIGNMENT.HARDENING * depth);
    }
    if (amount < 0) lastCrueltyAt = state.time;

    alignTarget = THREE.MathUtils.clamp(alignTarget + scaled, -1, 1);
    if (why) state.debug.lastLog = `${why} (alignment ${alignTarget >= 0 ? '+' : ''}${alignTarget.toFixed(2)})`;
  }

  if (state.events) {
    // Only deeds the player is responsible for move alignment. A rival's
    // soldiers putting your farmers to the sword is something done TO you, and
    // charging it to your soul would be exactly backwards. Events without the
    // flag are the player's by default, which is what every older emitter is.
    state.events.on('villagers-killed', (e) => {
      if (e.byPlayer === false) return;
      const per = e.cause === 'creature' ? ALIGNMENT.CREATURE_ATE_VILLAGER
        : e.cause === 'soldiers' ? COMBAT.ALIGN_PER_CIVILIAN
          : ALIGNMENT.CRUSH_VILLAGER;
      shiftAlignment(per * e.count, `${e.count} villager${e.count > 1 ? 's' : ''} died`);
    });
    state.events.on('building-destroyed', (e) => {
      if (e && e.byPlayer === false) return;
      shiftAlignment(ALIGNMENT.DESTROY_OWN_BUILDING, 'a building was destroyed');
    });
    state.events.on('villagers-fed', () =>
      shiftAlignment(ALIGNMENT.FEED_VILLAGER, 'you fed your people'));
    // Raising something for your people is a kindness. Mercy only - it pays no
    // belief. Yours alone, too: a rival's barn is not your good deed.
    state.events.on('building-placed', (e) => {
      if (!e?.byPlayer) return;
      const mercy = e.def?.mercy ?? 0.5;
      if (mercy <= 0) return;
      shiftAlignment(ALIGNMENT.RAISE_BUILDING * mercy, `you raised a ${e.def.label}`);
    });
    state.events.on('villager-born', () =>
      shiftAlignment(ALIGNMENT.VILLAGER_BORN));
    // Sparing vs razing: how a town is taken is the heaviest moral act in the
    // game, so it moves alignment further than anything else.
    /**
     * A prayer ended. Turn it into belief, and sometimes into judgement.
     *
     * Belief is this module's to own - prayers.js never touches it - so the
     * prayer system announces the fact and the payment happens here, next to
     * every other rule about what faith is worth.
     *
     * The amounts are deliberately small. One prayer must never swing a town:
     * for scale, the passive trickle is around 15 belief a minute, an answered
     * prayer is 6, and letting one lapse costs 2.5.
     */
    state.events.on('prayer-resolved', (e) => {
      if (e.status === 'answered') {
        // Nobody gets divine credit for a crisis that solved itself.
        if (e.by === 'nobody' || e.by === 'none') return;
        let paid = PRAYER.BELIEF_ANSWERED;
        // MERCY FOR ANSWERING, always - not only when it was urgent and not
        // only when it was quick. Somebody asked you for help by name and you
        // came; that is the plainest kind act available to a god in this game.
        let mercy = PRAYER.ALIGN_ANSWERED;
        if (e.urgency >= PRAYER.URGENT_AT) mercy += PRAYER.ALIGN_ANSWERED_URGENT;
        shiftAlignment(mercy, `you answered ${e.category}`);

        // Speed is paid in belief rather than in character: turning up fast is
        // impressive, turning up at all is what makes you merciful.
        if (e.urgency >= PRAYER.URGENT_AT && e.age <= PRAYER.PROMPT_SECONDS) {
          paid += PRAYER.BELIEF_PROMPT_BONUS;
        }
        state.resources.belief = Math.min(MIRACLE.MAX_BELIEF,
          state.resources.belief + paid);
        return;
      }

      if (e.status === 'expired' || e.status === 'failed') {
        const lost = e.status === 'failed' ? PRAYER.BELIEF_FAILED : PRAYER.BELIEF_EXPIRED;
        state.resources.belief = Math.max(0, state.resources.belief + lost);

        // EVERY unanswered prayer leans cruel, not every fourth. Someone asked
        // you by name and you did not come; dying while still asking is worse
        // than giving up on you, and being ignored while desperate is worse
        // than being ignored while merely uncomfortable.
        let cruelty = e.status === 'failed'
          ? PRAYER.ALIGN_FAILED : PRAYER.ALIGN_EXPIRED;
        if (e.urgency >= PRAYER.URGENT_AT) cruelty *= PRAYER.URGENT_NEGLECT_MULT;
        shiftAlignment(cruelty, `you did not answer ${e.category}`);

      }
      neglectStreak = e.neglectStreak ?? 0;
      // 'invalid' pays and costs nothing: the question stopped existing.
    });

    state.events.on('town-captured', (e) => shiftAlignment(
      e.how === 'conquest' ? COMBAT.ALIGN_CONQUEST : COMBAT.ALIGN_PEACEFUL,
      e.how === 'conquest' ? `${e.town.name} was conquered` : `${e.town.name} joined you willingly`
    ));
  }

  // --- belief ---------------------------------------------------------------
  // The player opens with a working god's worth of it. See MIRACLE.START_BELIEF
  // - and note this assignment is why the constant lives there and not in TOWN:
  // miracles.js initialises after town.js, so anything town.js set is gone.
  state.resources.belief = MIRACLE.START_BELIEF;

  // --- casting --------------------------------------------------------------
  //
  // Hold Ctrl and the mouse becomes a casting tool: the wheel picks the
  // miracle, left click places it, letting go puts it away. There is no armed
  // mode to get stuck in and nothing to disarm, which is the whole appeal -
  // the state lasts exactly as long as you are holding the key.
  //
  // One miracle is always SELECTED. That is a preference, not a mode: it does
  // nothing at all until Ctrl is down.
  const SPELLS = Object.keys(MIRACLES);
  let selected = SPELLS[0];
  let lastResult = null;
  let lastResultTimer = 0;

  const raycaster = new THREE.Raycaster();
  const castPlane = new THREE.Plane(new THREE.Vector3(0, 1, 0), 0);
  const _hit = new THREE.Vector3();

  /**
   * The ground each miracle actually covers. Taken from the same constants the
   * effects use, so the circle you are shown is the circle you get.
   */
  const FOOTPRINT = {
    water: MIRACLE.WATER_RADIUS,
    food: MIRACLE.FOOD_RADIUS,
    fireball: MIRACLE.FIRE_RADIUS,
    lightning: MIRACLE.LIGHTNING_RADIUS
  };

  // A ring under the cursor while Ctrl is held. Without it the casting state
  // lives entirely in a highlighted row in the corner of the screen, which is
  // a poor place to look when you are aiming at a field.
  const aimGeo = new THREE.RingGeometry(0.94, 1.0, 64);
  aimGeo.rotateX(-Math.PI / 2);
  const aimMat = new THREE.MeshBasicMaterial({
    transparent: true, opacity: 0.6, depthWrite: false, side: THREE.DoubleSide
  });
  const aim = new THREE.Mesh(aimGeo, aimMat);
  aim.visible = false;
  aim.renderOrder = 3;
  state.scene.add(aim);

  /** True while the caster's key is held. This is the entire mode. */
  function isCasting() {
    const i = state.input;
    return i.keyDown('ControlLeft') || i.keyDown('ControlRight');
  }

  function updateAim() {
    if (!isCasting()) { aim.visible = false; return; }
    const at = cursorTarget();
    if (!at) { aim.visible = false; return; }
    const def = MIRACLES[selected];
    aim.visible = true;
    aim.position.set(at.x, terrain.heightAt(at.x, at.z) + 0.35, at.z);
    aim.scale.setScalar(FOOTPRINT[selected] ?? 12);
    aimMat.color.setHex(def.color);
    // Dimmed when you cannot pay, so a miracle you cannot afford does not
    // look identical to one you can.
    aimMat.opacity = state.resources.belief >= def.cost ? 0.6 : 0.2;
  }

  /**
   * Your own villagers close enough to see a miracle at `at`, and their
   * combined devotion.
   *
   * A linear scan: it runs once per cast, not per tick, and 150 distance tests
   * on a button press is not worth a spatial hash.
   */
  function witnessesOf(at) {
    const list = state.villagers?.list ?? [];
    const r2 = MIRACLE.WITNESS_RADIUS * MIRACLE.WITNESS_RADIUS;
    let count = 0;
    let faith = 0;
    for (const v of list) {
      if (!v.alive || !v.town?.isPlayer) continue;
      const d2 = (v.pos.x - at.x) ** 2 + (v.pos.z - at.z) ** 2;
      if (d2 > r2) continue;
      count++;
      faith += v.mods?.belief ?? 1;
    }
    return { count, faith };
  }

  /** The world point under the cursor: the terrain if it is hit, else sea level. */
  function cursorTarget() {
    raycaster.setFromCamera(state.input.ndc, state.camera.cam);
    const hits = raycaster.intersectObject(terrain.mesh, false);
    if (hits.length) return hits[0].point.clone();
    castPlane.constant = -WORLD.SEA_LEVEL;
    return raycaster.ray.intersectPlane(castPlane, _hit) ? _hit.clone() : null;
  }

  // --- the miracles ---------------------------------------------------------
  function cast(key, at) {
    const def = MIRACLES[key];
    if (!def || !at) return { ok: false, reason: 'nowhere to cast' };

    // Castable in your own land OR anywhere a rival can see - impressing them
    // requires working wonders where they will actually witness it.
    if (!state.town.inInfluence(at.x, at.z) && state.town.townsWatching(at.x, at.z).length === 0) {
      return { ok: false, reason: 'no one here to witness it' };
    }
    if (state.resources.belief < def.cost) {
      return { ok: false, reason: `needs ${def.cost} belief` };
    }
    state.resources.belief -= def.cost;

    switch (key) {
      case 'water': {
        const r = MIRACLE.WATER_RADIUS;
        // EVERY farm you hold, not just your capital's. `state.town.buildings`
        // is the player's founding town alone, so watering a field in a town
        // you had captured did nothing at all - and the new `thirst` prayer can
        // be raised by any town you hold, which would have made it unanswerable
        // in exactly the places you had worked hardest to get.
        for (const b of state.town.allBuildings) {
          if (!b.def.farm || !b.town.isPlayer) continue;
          if (Math.hypot(b.pos.x - at.x, b.pos.z - at.z) < r) {
            b.crop = Math.min(1, b.crop + def.cropBoost);
          }
        }
        // Rain also washes the creature.
        if (state.creature && state.creature.position.distanceTo(at) < r * 1.5) {
          state.creature.needs.cleanliness = Math.min(1, state.creature.needs.cleanliness + 0.5);
        }
        for (let i = 0; i < 8; i++) {
          const a = Math.random() * Math.PI * 2;
          const d = Math.random() * r;
          state.fx?.splash(
            new THREE.Vector3(at.x + Math.cos(a) * d, at.y, at.z + Math.sin(a) * d), 10);
        }
        break;
      }

      case 'food': {
        state.resources.food += def.foodGranted;
        // Villagers nearby eat their fill immediately.
        if (state.villagers) {
          for (const v of state.villagers.list) {
            if (!v.alive) continue;
            if (Math.hypot(v.pos.x - at.x, v.pos.z - at.z) < MIRACLE.FOOD_RADIUS) v.hunger = 0;
          }
        }
        state.events?.emit('villagers-fed', { pos: at, cause: 'miracle' });
        state.fx?.burst(at, 26, def.color);
        break;
      }

      case 'fireball': {
        const r = MIRACLE.FIRE_RADIUS;
        terrain.deform(at.x, at.z, r * 0.8, -def.craterDepth);
        let killed = 0;
        if (state.villagers) {
          for (const v of state.villagers.list) {
            if (!v.alive) continue;
            if (Math.hypot(v.pos.x - at.x, v.pos.z - at.z) < r) { v.alive = false; killed++; }
          }
        }
        for (const b of [...state.town.buildings]) {
          if (Math.hypot(b.pos.x - at.x, b.pos.z - at.z) < r) {
            state.town.demolish(b);
            state.events?.emit('building-destroyed',
              { building: b, pos: at, cause: 'fireball', byPlayer: true, by: 0 });
          }
        }
        // Blow loose props outward.
        for (const p of state.props.list) {
          if (p.dead || p.harvested || p.held) continue;
          const d = Math.hypot(p.pos.x - at.x, p.pos.z - at.z);
          if (d > r * 2) continue;
          const f = (1 - d / (r * 2)) * 45;
          p.vel.x += ((p.pos.x - at.x) / (d || 1)) * f;
          p.vel.z += ((p.pos.z - at.z) / (d || 1)) * f;
          p.vel.y += f * 0.7;
          state.props.wake(p);
        }
        if (killed) state.events?.emit('villagers-killed',
          { count: killed, pos: at, cause: 'fireball', byPlayer: true, by: 0 });
        state.fx?.burst(at, 40, def.color);
        break;
      }

      case 'lightning': {
        const r = MIRACLE.LIGHTNING_RADIUS;
        terrain.deform(at.x, at.z, r * 0.7, -def.craterDepth);
        let killed = 0;
        if (state.villagers) {
          for (const v of state.villagers.list) {
            if (!v.alive) continue;
            if (Math.hypot(v.pos.x - at.x, v.pos.z - at.z) < r) { v.alive = false; killed++; }
          }
        }
        for (const b of [...state.town.buildings]) {
          if (Math.hypot(b.pos.x - at.x, b.pos.z - at.z) < r * 0.8) {
            state.town.demolish(b);
            state.events?.emit('building-destroyed',
              { building: b, pos: at, cause: 'lightning', byPlayer: true, by: 0 });
          }
        }
        if (killed) state.events?.emit('villagers-killed',
          { count: killed, pos: at, cause: 'lightning', byPlayer: true, by: 0 });
        state.fx?.burst(at, 30, def.color);
        // A quick vertical column of sparks reads as the strike itself.
        for (let i = 0; i < 26; i++) {
          state.fx?.burst(
            new THREE.Vector3(at.x + (Math.random() - 0.5) * 2, at.y + i * 1.6, at.z + (Math.random() - 0.5) * 2),
            2, def.color);
        }
        break;
      }
    }

    // Rivals who can see this judge you by it: wonders win them over, cruelty
    // hardens them. This is the peaceful route to taking a town.
    for (const t of state.town.townsWatching(at.x, at.z)) {
      const awe = def.align > 0
        ? TOWN.IMPRESS_PER_MIRACLE * (def.cost / 30)
        : TOWN.IMPRESS_MIRACLE_CRUELTY;
      state.town.addImpressiveness(t, awe, 'miracle');
    }

    shiftAlignment(def.align, `cast ${def.label}`);
    state.events?.emit('miracle-cast', { key, def, pos: at.clone() });

    // --- who saw it ---
    //
    // Your own people only. A rival's villagers watching you work a wonder
    // feeds their awe, not your belief - they are impressed, not converted, and
    // that route is already handled above.
    const seen = witnessesOf(at);
    let paid = 0;
    if (seen.count > 0) {
      paid = Math.min(
        seen.faith * MIRACLE.BELIEF_PER_WITNESS,
        def.cost * MIRACLE.WITNESS_MAX_REFUND
      );
      state.resources.belief = Math.min(MIRACLE.MAX_BELIEF, state.resources.belief + paid);
    }

    return { ok: true, witnesses: seen.count, refunded: paid };
  }

  // --- input ----------------------------------------------------------------
  function updateInput(dt) {
    const input = state.input;

    if (lastResultTimer > 0) {
      lastResultTimer -= dt;
      if (lastResultTimer <= 0) lastResult = null;
    }

    if (!isCasting()) return;

    // The wheel cycles the selection, and is CONSUMED so the camera does not
    // also zoom out from under you while you are choosing. Miracles run before
    // the hand and the camera for exactly this reason.
    if (input.wheel !== 0) {
      const dir = input.wheel > 0 ? 1 : -1;
      const at = SPELLS.indexOf(selected);
      selected = SPELLS[(at + dir + SPELLS.length) % SPELLS.length];
      input.wheel = 0;
      state.ui?.refreshGrimoire?.();
    }

    // Left click places it. Captured so the hand does not also try to grab
    // whatever is under the cursor.
    if (input.pressed[0] && !input.isCaptured('miracles')) {
      input.capture('miracles');
      const def = MIRACLES[selected];
      const res = cast(selected, cursorTarget());
      lastResult = res.ok
        ? {
            text: res.witnesses
              ? `${def.label} — ${res.witnesses} saw it, +${Math.round(res.refunded)} belief`
              : `${def.label} — nobody saw it`,
            key: selected
          }
        : { text: def.label + ': ' + res.reason, bad: true };
      lastResultTimer = 2.0;
    }

    if (input.released[0] && input.capturedBy === 'miracles') input.capturedBy = null;
  }

  /**
   * One of your own, thrown and landed alive.
   *
   * Called by villagers.js the moment they pick themselves up. Everyone who saw
   * it counts, including the one who was thrown - being hurled across your own
   * square by your god and living is the most direct evidence of him anybody in
   * this town will ever get.
   */
  function thrownBeliever(v, from, to) {
    if (!v || !v.alive || !v.town?.isPlayer) return 0;
    if (!from || from.distanceTo(to) < MIRACLE.THROW_MIN_DIST) return 0;
    if (v.thrownPaidAt && state.time - v.thrownPaidAt < MIRACLE.THROW_COOLDOWN) return 0;

    const seen = witnessesOf(to);
    if (!seen.count) return 0;

    v.thrownPaidAt = state.time;
    const paid = Math.min(seen.faith * MIRACLE.BELIEF_PER_THROW_WITNESS,
                          MIRACLE.THROW_MAX_BELIEF);
    state.resources.belief = Math.min(MIRACLE.MAX_BELIEF, state.resources.belief + paid);
    lastResult = { text: `flung and lived — ${seen.count} saw it, +${paid.toFixed(1)} belief` };
    lastResultTimer = 1.8;
    return paid;
  }

  /**
   * The hand cleared something out of a lived-in place.
   *
   * Called by hand.js on release with where the thing was picked up and where
   * it ended up. Belief only for a real move, only if someone was there to see
   * the ground cleared, and only once per object per cooldown - otherwise the
   * whole thing is juggling one rock in a crowd.
   */
  function clearedGround(from, to, prop) {
    if (!from || !to || !prop) return 0;
    if (from.distanceTo(to) < MIRACLE.CLEAR_MIN_DIST) return 0;
    if (prop.clearedAt && state.time - prop.clearedAt < MIRACLE.CLEAR_COOLDOWN) return 0;

    const seen = witnessesOf(from);
    if (!seen.count) return 0;

    prop.clearedAt = state.time;
    const paid = Math.min(seen.faith * MIRACLE.BELIEF_PER_CLEARED,
                          MIRACLE.CLEAR_MAX_BELIEF);
    state.resources.belief = Math.min(MIRACLE.MAX_BELIEF, state.resources.belief + paid);
    lastResult = { text: `cleared their land — ${seen.count} saw it, +${paid.toFixed(1)} belief` };
    lastResultTimer = 1.6;
    return paid;
  }

  /** Choose which miracle Ctrl will cast. Does not itself arm anything. */
  function select(key) {
    if (!MIRACLES[key]) return false;
    selected = key;
    state.ui?.refreshGrimoire?.();
    return true;
  }

  // --- simulation -----------------------------------------------------------
  function simStep(dt) {
    // Belief accrues from a happy, populated town. Counted per head rather than
    // as a flat population, because a Devout villager prays for four Doubters -
    // which is the only thing that makes those two traits worth having.
    const faith = state.villagers ? state.villagers.faith : 0;
    const happiness = state.town ? state.town.happiness : 0;
    state.resources.belief = Math.min(
      MIRACLE.MAX_BELIEF,
      state.resources.belief + faith * MIRACLE.BELIEF_PER_VILLAGER * happiness * dt
    );

    // Penance: cruelty fades if you stop feeding it. Only ever toward neutral,
    // and only from the cruel side - see ALIGNMENT.PENANCE_RATE.
    // Penance still runs, and still forgives what you did and then stopped
    // doing - but it cannot lift you above the level your unanswered prayers
    // hold you at. Ignoring people is not "stopping"; it is the ongoing act.
    // See PRAYER.NEGLECT_FLOOR_PER for why this is a floor rather than a
    // suspension: suspending it removed the safety valve for every other
    // cruelty too, and an idle god ended up damned mostly by their creature.
    const neglectFloor = -Math.min(
      PRAYER.NEGLECT_FLOOR_MAX, neglectStreak * PRAYER.NEGLECT_FLOOR_PER
    );
    if (alignTarget < neglectFloor) {
      const clean = state.time - lastCrueltyAt >= ALIGNMENT.PENANCE_AFTER;
      const rate = ALIGNMENT.PENANCE_RATE * (clean ? 2 : 1);
      alignTarget = Math.min(neglectFloor, alignTarget + rate * dt);
    }

    // Alignment eases toward its target so the world does not flicker.
    const k = 1 - Math.exp(-ALIGNMENT.SMOOTH * dt);
    state.alignment += (alignTarget - state.alignment) * k;
  }

  function update(dt) {
    updateInput(dt);
    updateAim();
    // Terrain saturation follows alignment.
    terrain.setAlignment(state.alignment);
  }

  const api = {
    enabled: true,
    cast,
    clearedGround,
    thrownBeliever,
    select,
    /** Which miracle Ctrl would cast. Always set. */
    get selected() { return selected; },
    /** True while the caster's key is held. */
    get casting() { return isCasting(); },
    get lastResult() { return lastResult; },
    get alignment() { return state.alignment; },
    get alignmentTarget() { return alignTarget; },
    shiftAlignment,
    simStep,
    update
  };
  state.miracles = api;
  return api;
}
